%%{
    init: {
        'theme':'forest'
    }}%%


flowchart TB
  

    subgraph DeveloperPath[Container Orchestration]
    end 
    subgraph Simple[Simple code\nor container\nwithout orchestration]
    end
    subgraph  Advanced[Advanced\ncontainer\norchestration]
    end

    subgraph SuggestedService[ ]

        subgraph SimpleService[Azure App Service\nAzure Spring Apps\nAzure Container Apps\nAzure Container Instance]
        end

        subgraph AdvancedService[Azure Kubernetes Service\nAzure Service Fabric]
        end

    end


    DeveloperPath --> Advanced 
    DeveloperPath --> Simple 

    Simple --> SimpleService
    Advanced --> AdvancedService


