%%{
    init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#0072C6',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#00A3E0',
      'lineColor': '#F8B229',
      'secondaryColor': '#006100',
      'tertiaryColor': '#8E8E8E'
    }
    }}%%


flowchart TB
  

    subgraph DeveloperPath[Source code]
    end 
    subgraph  NoLowCode[No code \nor low code]
    end
    subgraph Code[Code]
    end
    subgraph Containers[Container]
    end

    subgraph Enterprise[Enterprise or \nBusiness to business]
    end
    subgraph Client[Client \nor Client + API]
    end

    subgraph Stateful[Stateful]
    end

    subgraph Stateless[Stateless]
    end
    subgraph Full[Full stack\nor API\nor Server\nor Automation]
    end
    subgraph SuggestedService[ ]

        subgraph PowerLogic[Power Apps \nor Logic Apps]
        end

        subgraph SWA[Azure Static Web Apps \n + Azure Functions Apps]
        end

        subgraph Server[Azure App Service\nAzure Spring Apps]
        end

        subgraph FunctionApps[Azure Functions Apps]
        end

        subgraph ContainerApps[Azure Container Apps]
        end


    end


    DeveloperPath --> NoLowCode 
    DeveloperPath --> Code 
    DeveloperPath --> Containers 

    NoLowCode --> Enterprise --> PowerLogic
    Code --> Client
    Code --> Stateless
    Code --> Full

    Client --> SWA
    Full --> Server

    Containers --> Stateful --> ContainerApps
    Containers --> Stateless --> FunctionApps
