%%{
    init: {
        'theme':'forest'
    }}%%


flowchart TB
  

    subgraph DeveloperPath[Source code]
    end 
    subgraph  NoLowCode[No code \nor low code]
    end
    subgraph Code[Code]
    end
    subgraph Containers[Container]
    end

    subgraph Enterprise[Enterprise or \nBusiness to business]
    end
    subgraph Client[Client \nor Client + API]
    end

    subgraph Stateful[Stateful]
    end

    subgraph Stateless[Stateless]
    end
    subgraph Full[Full stack\nor Server\nor Automation]
    end
    subgraph SuggestedService[ ]

        subgraph SWA[Azure Static Web Apps \n + Azure Functions Apps]
        end

        subgraph PowerLogic[Power Apps \nor Logic Apps]
        end

        subgraph Server[Azure App Service\nAzure Spring Apps]
        end

        subgraph ContainerApps[Azure Container Apps]
        end

        subgraph FunctionApps[Azure Functions Apps]
        end
    end


    DeveloperPath --> NoLowCode 
    DeveloperPath --> Code 
    DeveloperPath --> Containers 

    NoLowCode --> Enterprise --> PowerLogic
    Code --> Client
    Code --> Full


    Full --> Server

    Client --> SWA

    Containers --> Stateful --> ContainerApps
    Containers --> Stateless --> FunctionApps

