graph LR
    A[TypeSpec API Definition]:::green
    B[Generate API Specification]:::green
    C[Generate API Code]:::grey

    A --> B
    B --> C


    classDef green fill:#80FF80,stroke:#333,stroke-width:2px;
    classDef grey fill:#E0E0E0,stroke:#333,stroke-width:2px;