copy \source\repos\azure-dev-docs-pr\java\includes\migration\inventory-external-resources.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\inventory-secrets.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\inventory-persistence-usage.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\inventory-external-resources.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\inventory-secrets.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\inventory-persistence-usage.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\inventory-server-capacity-virtual-machines.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\inventory-all-secrets.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\inventory-all-certificates.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\validate-that-the-supported-java-version-works-correctly.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\inventory-jndi-resources.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\domain-configuration.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-session-replication-is-used.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\document-datasources.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-weblogic-has-been-customized.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-management-over-rest-is-used.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-a-connection-to-on-premises-is-needed.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-jms-queues-or-topics-are-being-used-virtual-machines.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-you-are-using-your-own-custom-created-shared-java-ee-libraries.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-osgi-bundles-are-used.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-your-application-contains-os-specific-code.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-oracle-service-bus-is-being-used.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-your-application-is-composed-of-multiple-wars.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-your-application-is-packaged-as-an-ear.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\identify-all-outside-processes-and-daemons-running-on-the-production-servers.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-wlst-is-used.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\validate-if-and-how-the-file-system-is-used.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-the-network-topology.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\account-for-the-use-of-jca-adapters-and-resource-adapters.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\account-for-the-use-of-custom-security-providers-and-jaas.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-weblogic-clustering-is-used.md includes\migration
copy \source\repos\azure-dev-docs-pr\java\includes\migration\determine-whether-the-java-ee-application-client-feature-is-used.md includes\migration
